############################################################
#
# Home Assistant Binary Sensors
#
############################################################
# https://github.com/kloggy/HA-Irrigation-Version2
# If rain data has changed in the last 30 mins, then its raining.
# - platform: template
#   sensors:
#     raining_now:
#       friendly_name: "Raining Now"
#       value_template: >-
#         {{ state_attr('sensor.local_rain_30_min_statistics_raw', 'change')|float > 0 }}

- platform: template
  sensors:
    raining_now:
      friendly_name: "Raining Now"
      value_template: "{{ is_state('sensor.openweathermap_precipitation_kind', 'Rain') }}"

          # value_template: >-
          #   {% if is_state("sensor.openweathermap_precipitation_kind", "Rain") -%}
          #     true
          #   {%- else -%}
          #     false
          #   {%- endif %}              

############################################################
#
# Doorbells
#
############################################################

# - platform: mqtt
#   state_topic: "HUISHS/Doorbell/Alert"
#   name: "Doorbell"
#   qos: 0
#   payload_on: "1"
#   payload_off: "0"


# - platform: mqtt
#   state_topic: !secret
#   name: "ESP-Link"
#   qos: 0
#   device_class: connectivity
#   value_template: '{{ value_json.batt }}'

#From examples...
# - platform: mqtt
#   state_topic: "house/controller/1"
#   name: "Summer House"
#   qos: 0
#   payload_on: "2"
#   payload_off: "2 off"
#   sensor_class: motion

# - platform: mqtt
#   state_topic: "house/controller/1"
#   name: "Driveway"
#   qos: 0
#   payload_on: "6"
#   payload_off: "6 off"
#   sensor_class: motion

# - platform: mqtt
#   state_topic: "house/controller/1"
#   name: "Courtyard"
#   qos: 0
#   payload_on: "1"
#   payload_off: "1 off"
#   sensor_class: motion


# Sun2 Sensor https://github.com/pnbruckner/ha-sun2
# For https://github.com/kloggy/HA-Irrigation-Version2/blob/master/Pre-Requisites.md
- platform: sun2
  monitored_conditions:
    - elevation