##############################################################
# Richard Huish 2022
# https://github.com/genestealer/Home-Assistant-Configuration
# Indoor Air Quality Sensor #2
##############################################################
# Config Header for Device
##############################################################
substitutions:
  # Used by ESP Home
  device_name: air-quality-sensor-2
  # Used by ESP Home
  device_description: "Indoor Air Quality Sensor 2"
  # Prefix used by Wifi IP, RSSI etc
  upper_devicename: "Indoor Air Filter 2"
  # Prefix used by main Inputs & Outputs
  short_devicename: "Air Filter 2"
  ip: 192.168.2.45
  pass: hxN#^fPPv5ZRy%7l

  status_led: LED_RED
  platform: ESP8266
  board: huzzah
  throttle_setting: "60s"
  median_window_size: "6"
  median_send_every: "4"
  median_send_first_at: "3"
  
##############################################################
# Shared code from all my projects
##############################################################
esphome:
  name: ${device_name}
  comment: ${device_description}
  platform: ${platform}
  board: ${board}
  
wifi:
  ssid: !secret IoT_VLAN_SSID
  password: !secret IoT_VLAN_SSID_Key
  manual_ip:
    static_ip: $ip
    gateway: 192.168.2.1
    subnet: 255.255.255.0

logger: # Enable logging

api: # Enable Home Assistant API
  password: $pass

ota: # Enable over the air updates
  password: $pass
  safe_mode: true
  reboot_timeout: 10min
  num_attempts: 5

# Status LED for connection
status_led:
  pin:
    number: ${status_led}
    inverted: true

##############################################################
# Non-Shared Code (May contain shared code)
##############################################################

text_sensor:
# Shared code beginning... 
  # Wifi Data
  - platform: wifi_info  
    ip_address:
      name: ${upper_devicename} IP
      icon: "mdi:ip-network-outline"
    ssid:
      name: ${upper_devicename} SSID
      icon: "mdi:help-network-outline"
    bssid:
      name: ${upper_devicename} BSSID
      icon: "mdi:access-point-network"
# ...shared code end

binary_sensor:
# Shared code beginning... 
  # Device avaliablity
  - platform: status  
    name: ${upper_devicename} Status
    device_class: connectivity
# ...shared code end

sensor:
# Shared code beginning... 
  # Wifi signal strength
  - platform: wifi_signal
    name: ${upper_devicename} RSSI
    update_interval: 300s
    # icon: "mdi:access-point-network"
    device_class: signal_strength
    state_class: measurement
# ...shared code end
    
  # pmsx003 Air sensor
  - platform: pmsx003
    type: PMSX003
    pm_0_3um:
      name: "${short_devicename} PM <0.3um in 0.1L of air"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_0_5um:
      name: "${short_devicename} PM <0.5um in 0.1L of air"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_1_0um:
      name: "${short_devicename} PM <1.0um in 0.1L of air"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_2_5um:
      name: "${short_devicename} PM <2.5um in 0.1L of air"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_5_0um:
      name: "${short_devicename} PM <5.0um in 0.1L of air"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_10_0um:
      name: "${short_devicename} PM <10.0um in 0.1L of air"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    
    pm_1_0:
      name: "${short_devicename} PM <1.0µm Concentration"
      device_class: "pm1"
      state_class: "measurement"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_2_5:
      name: "${short_devicename} PM <2.5µm Concentration"
      device_class: "pm25"
      state_class: "measurement"
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}
    pm_10_0:
      name: "${short_devicename} PM <10.0µm Concentration"
      device_class: pm10
      state_class: measurement
      filters:
        - throttle: ${throttle_setting}
        - median:
           window_size: ${median_window_size}
           send_every: ${median_send_every}
           send_first_at: ${median_send_first_at}


# Serial for pmsx003
# huzzah The RX pin is the input into the module and is 5V compliant (there is a level shifter on this pin)
uart:
  rx_pin: GPIO13
  baud_rate: 9600
  
